version: '3.8'
services:
  redis:
    image: redis:alpine
    volumes:
      - ./volumes/redis:/data

  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    env_file:
      - .env
    command: sh -c "cd ./src && uvicorn main:app --host 0.0.0.0 --port 80 --reload"
